---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  measurements:
    - name: vmiLatency
      thresholds:
        - conditionType: VMIRunning
          metric: P99
          threshold: {{.VMI_RUNNING_THRESHOLD}}
metricsEndpoints:
{{ if .ES_SERVER }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      esServers: ["{{.ES_SERVER}}"]
      insecureSkipVerify: true
      defaultIndex: {{.ES_INDEX}}
      type: opensearch
{{ end }}
{{ if eq .LOCAL_INDEXING "true" }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      type: local
      metricsDirectory: collected-metrics-{{.UUID}}
{{ end }}
jobs:
  - name: create-cudn-loclanet
    namespace: virt-density-client
    jobIterations: 1
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: false
    podWait: false
    waitWhenFinished: true
    preLoadImages: true
    jobPause: 10s
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:
      - objectTemplate: cudn-localnet.yml
        replicas: 1

  - name: virt-udn-localnet-density
    namespace: virt-density-client
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: false
    preLoadImages: true
    waitWhenFinished: true
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:

      - objectTemplate: vm-client.yml
        replicas: 1
        inputVars:
          vmImage: {{.VM_IMAGE}}
      - objectTemplate: vm-server.yml
        replicas: 1
        inputVars:
          vmImage: {{.VM_IMAGE}}
